import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Bio from '../components/Bio';
import Post from '../components/Post';
import PostForm from '../components/PostForm';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Bio
          headshot='https://pbs.twimg.com/profile_images/845865860753494017/hb9FhkE0_400x400.jpg'
          name='Khalid'
          tagline='Front-end developer'
          role='Some content'
        />
        <ul className={styles.posts}>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
        </ul>

        <PostForm />
      </main>
    </div>
  );
}
