import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import Post from '../components/Post';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>My Posts</h1>

        <ul className={styles.posts}>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
          <li>
            <Post
              content='I’m working in Figma trying to design a new website that shows all
              of my tweets!'
              date='3/2/2022'
            />
          </li>
        </ul>

        <form action=''>
          <textarea className={styles.formContent}></textarea>
          <button className={styles.formButton}>Add New Post</button>
        </form>
      </main>
    </div>
  );
}
